version: '3.9'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: epklabs/music-app-frontend
    container_name: music-app-frontend
    restart: unless-stopped
    ports:
      - '3030:80' # change to your desired port on the left side of the colon. Do not touch the right side
    depends_on:
      - server
    networks:
      - mynetwork
    environment:
      - VITE_API_URL
      - VITE_HOME_TITLE
      - VITE_SPOTIFY_LINK
      - VITE_APPLE_LINK
      - VITE_AMAZON_LINK
      - VITE_YOUTUBE_LINK
      - VITE_SOUNDCLOUD_LINK

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: epklabs/music-app-server
    container_name: music-app-server
    restart: unless-stopped
    ports:
      - '3001:3001' # change to your desired port on the left side of the colon. Do not touch the right side
    volumes:
      - /path/to/images:/app/public # change to your desired path on the left side of the colon. It must be in a folder called Images. Do not touch the right side
      - /path/to/music:/app/public # change to your desired path on the left side of the colon. It must be in a folder called Music. Do not touch the right side
    networks:
      - mynetwork
    environment:
      - SITE_URL

networks:
  mynetwork:
