version: '3.9'

services:
  # frontend:
  #   build:
  #     context: ./front-end
  #     dockerfile: Dockerfile
  #   image: epklabs/music-app-frontend
  #   container_name: music-app-frontend
  #   restart: unless-stopped
  #   ports:
  #     - '3030:80'
  #   depends_on:
  #     - server
  #   networks:
  #     - mynetwork

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: epklabs/music-app-server
    container_name: music-app-server
    volumes:
      - /mnt/server/db/music:/public
    restart: unless-stopped
    ports:
      - '3001:3001'
