version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: your-username/music-app-frontend
    container_name: music-app-frontend
    ports:
      - '80:80'
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: your-username/music-app-server
    container_name: music-app-server
    ports:
      - '3001:3001'
    volumes:
      - /mnt/server/files:/app/public
